version: "2"

linters:
  default: all
  disable:
    - wsl
    - wsl_v5
    - exhaustruct
    - testpackage
    - varnamelen
    - nlreturn
    - forcetypeassert
    - funlen
    - depguard
run:
  timeout: 3m
